create table passengers(
  passenger_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  first_name varchar(50), last_name varchar(50), dateofbrith date,
  countryOfcitizenship varchar(50), countryOfresidence varchar(50),
  passport_number varchar(50), create_at timestamp, update_at timestamp, 
  primary key(passenger_id),
  CONSTRAINT passenger_id_length_check CHECK (passenger_id >= 1000000000 AND passenger_id <= 9999999999)
);

create table booking(
  booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  status varchar(20), booking_platform varchar(20),
  create_at timestamp, update_at timestamp, 
  primary key(booking_id), 
  passenger_id bigint references passengers(passenger_id),
  flight_id bigint references flights(flight_id),
   CONSTRAINT booking_id_length_check CHECK (booking_id >= 10000000070 AND booking_id <= 9999999999)
);


create table security_check(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  check_result varchar(20), comments varchar(65535),
  create_at timestamp, update_at timestamp, 
  primary key(id), passenger_id bigint references passengers(passenger_id),
  CONSTRAINT id_length_check CHECK (id >= 10000000070 AND id <= 9999999999)
);

create table airport(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  airport_name varchar(50), country varchar(50),
  state varchar(50), city varchar(50), 
  create_at timestamp, update_at timestamp, 
  primary key(id)
);

create table airline(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  airline_code varchar, airline_name varchar,
  airline_country varchar(50), create_at timestamp, update_at timestamp, 
   primary key(id)
);

create table flights(
  flight_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  departing_gate varchar(20), arriving_gate varchar(20),
   create_at timestamp, update_at timestamp, 
   airline_id bigint references airline(id),
   departing_id bigint references airport(id),
   arriving_id bigint references airport(id),
   primary key(flight_id)
);

create table baggage_check(
   id BIGINT GENERATED BY DEFAULT AS IDENTITY,
   check_result varchar(50), create_at timestamp, update_at timestamp, 
   booking_id bigint references booking(booking_id),
   passenger_id bigint references passengers(passenger_id),
   primary key(id)
);

create table no_fly_list(
   id BIGINT GENERATED BY DEFAULT AS IDENTITY,
   active_from date, active_to date, no_fly_reason varchar(255),
   create_at timestamp, update_at timestamp, 
  primary key(id), passenger_id bigint references passengers(passenger_id)
);

create table flight_manifest(
   id BIGINT GENERATED BY DEFAULT AS IDENTITY,
   create_at timestamp, update_at timestamp, 
   booking_id bigint references booking(booking_id),
   flight_id bigint references flights(flight_id),
   primary key(id)
);

create table boarding_pass(
   id BIGINT GENERATED BY DEFAULT AS IDENTITY,
   qr_code varchar,
   create_at timestamp, update_at timestamp, 
   booking_id bigint references booking(booking_id),
   primary key(id)
);

create table baggage(
   id BIGINT GENERATED BY DEFAULT AS IDENTITY,
   weight_in_kg decimal(4,2),
   create_at timestamp, update_at timestamp, 
   booking_id bigint references booking(booking_id),
   primary key(id)
);